name: Gitea Actions Demo
on: [push]
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build push
        uses: ./.github/actions/action-docker-build-push

      - run: echo The end
